// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAObn-TpIWvP8qsUwznVVvh_j-OxWbbr_E',
    appId: '1:115262937095:web:15067be5f358002aa6b2a2',
    messagingSenderId: '115262937095',
    projectId: 'ctree-c3569',
    authDomain: 'ctree-c3569.firebaseapp.com',
    storageBucket: 'ctree-c3569.firebasestorage.app',
    measurementId: 'G-D9CXQ6HGFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl-oroNLGFvRytUyQYm58r-frQQIfWzZ0',
    appId: '1:115262937095:android:af53cae8d15bafeba6b2a2',
    messagingSenderId: '115262937095',
    projectId: 'ctree-c3569',
    storageBucket: 'ctree-c3569.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvSrSuQbXFlZws7NTnBaOPb0KAx7cLrAg',
    appId: '1:115262937095:ios:8c506082ba003a4fa6b2a2',
    messagingSenderId: '115262937095',
    projectId: 'ctree-c3569',
    storageBucket: 'ctree-c3569.firebasestorage.app',
    iosBundleId: 'com.example.ctree',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvSrSuQbXFlZws7NTnBaOPb0KAx7cLrAg',
    appId: '1:115262937095:ios:8c506082ba003a4fa6b2a2',
    messagingSenderId: '115262937095',
    projectId: 'ctree-c3569',
    storageBucket: 'ctree-c3569.firebasestorage.app',
    iosBundleId: 'com.example.ctree',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAObn-TpIWvP8qsUwznVVvh_j-OxWbbr_E',
    appId: '1:115262937095:web:166589504873f3dda6b2a2',
    messagingSenderId: '115262937095',
    projectId: 'ctree-c3569',
    authDomain: 'ctree-c3569.firebaseapp.com',
    storageBucket: 'ctree-c3569.firebasestorage.app',
    measurementId: 'G-2YD6L5JYMF',
  );
}
